#
# Copyright (C) 2026 The Android Open Source Project
# Copyright (C) 2026 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_PATH := device/samsung/a14m

# Device uses dynamic partitions
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# Soong namespace for this tree
PRODUCT_SOONG_NAMESPACES += \
    $(LOCAL_PATH)

# Copy recovery root files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(LOCAL_PATH)/recovery/root,recovery/root)

# Filesystem tools needed by recovery
PRODUCT_PACKAGES += \
    fsck.f2fs \
    make_f2fs \
    sload_f2fs \
    mke2fs \
    e2fsdroid \
    resize2fs \
    tune2fs 

# Recovery services
PRODUCT_PACKAGES += \
    android.hardware.health-service.example_recovery \
    servicemanager \
    snapuserd

# Inherit proprietary blobs, if generated by extract-files.sh
$(call inherit-product-if-exists, vendor/samsung/a14m/a14m-vendor.mk)
